importProtoFilePath:
   - "./third_party"
protoFilePath: "./"
importFrom:
  - "import http from '@/api'"
ApiTemplate: "
  // {{.LeadingComments}}
  export const {{.Name}} = (params:{{.Request}}):Promise<{{.Resp}}> => {\n
    return http.{{.Method}}('{{.Path}}',params)\n
  }\n"
FuncCall:
  CreateDataSet: "function funcCall(leadingComments, name, Request, resp, method, path) {
        return `
        // ${leadingComments}
        export const ${name} = (params:${Request}):Promise<${resp}> => {\n
            return http.${method}('${path}',params,{noLoading:false})\n
        }\n`
    }"